### ISSUE TITLE
AprilTag Localization

### ISSUE THREAD

**Issue by FujiBookPro** [team401/2024-Robot-Code#11]
**Description**
We should be able to use cameras to estimate our position via AprilTags.

**Work Scope**
- [x] Create API/Subsystem to interface with AprilTag code
- [x] Set up and tune coprocessor running PhotonVision (or equivalent)
- [x] Wrap over coprocessor in an IO class using NetworkTables
- [x] Compute pose measurements from NT data

**Comment by PChild** [comment]
This can be a new issue if you all want, but can we also get [Photonvision sim](https://docs.photonvision.org/en/latest/docs/simulation/simulation.html) working? 

It would let us test our localization code even when we don't have access to the robot for extended periods of time and can produce video streams like this that would be cool to show judges

![](https://docs.photonvision.org/en/latest/_images/SimExampleFrame.png)

**Comment by linglejack06** [comment]
I actually already implemented that with a 2d field packaged in the navigation issue that we pushed to main. All it takes to make field 3d like above is add an extra method call, however, I did not implement it because photon vision states that it takes a lot of processing power to render the 3d field.

**Comment by jkleiber** [comment]
@linglejack06 maybe we can make the ticket to implement it, but hide it behind a flag so we can simulate it only when we want to (i.e. when we have the processing power)

**Comment by linglejack06** [comment]
yes that makes sense, i will go ahead and add that ticket

**Comment by jkleiber** [comment]
This is effectively done software wise, and the main work to do is to tune the kalman filter and make the BeeLink stay powered. Closing

**Comment by redPlover** [comment]
> This is effectively done software wise, and the main work to do is to tune the kalman filter and make the BeeLink stay powered. Closing

@jkleiber We tugged on one of the power wires for the beelink and it came out. We fixed this so it _could_ fix our issues.
