### ISSUE TITLE
Add support for the brake mode switch and the hour counter

### ISSUE THREAD

**Issue by jkleiber** [team401/2024-Robot-Code#114]
**Purpose**
The purpose of this addition is to add software support for the following two hardware devices, both enabled via Digital I/O:
- A switch that can set the motors for the aimer, hood, and climber into Coast mode when the robot is in Disabled. This switch would not be able to override Brake mode whenever the robot is enabled, but it would make it easier to manually position those systems prior to a match or after a match. If the switch is off in disabled, or if the robot gets enabled those motors should return to brake mode.
- A timer that counts up how long our robot has been enabled. All that needs to be done here is output a signal to this timer device using a Digital output whenever the robot is enabled and stop outputting that signal when the robot is disabled.

**Project Scope**
- [x] Update the scoring and climber subsystems to make it possible to set the mode to brake or coast programmatically
- [x] In disabledPeriodic, add logic to turn brake mode on or off for the mentioned subsystems based on the switch position
- [x] In disabledInit, set the timer output to OFF
- [x] In enabledInit, set the timer output to ON
- [x] In enabledInit, set the mentioned subsystems to be in brake mode

**Comment by redPlover** [comment]
@linglejack06 Whenever a DigitalInput is used without an attached Digital I/O on the robot, the code crashes. I would recommend creating some kind of checking system so that this doesn't happen if something gets unplugged.
