### ISSUE TITLE
Adds commit on deploy for comp branches

### ISSUE THREAD

**Issue by redPlover** [team401/2024-Robot-Code#122]
**Purpose**
We should have a gradle script that builds every time we deploy

**Project Scope**
- [x] Add build on deploy to build.gradle
- [x] Test if it only works in specified branches

**Comment by PChild** [comment]
can we do this today please?

**Comment by jkleiber** [comment]
[Ship it](https://cultofthepartyparrot.com/parrots/shipitparrot.gif)

**Comment by jkleiber** [comment]
Closing this untested ticket, hopefully it works tomorrow!
