### ISSUE TITLE
Update Phoenix API to latest

### ISSUE THREAD

**Issue by PChild** [team401/2024-Robot-Code#141]
**Purpose**
The purpose of this addition is to update all of our CTRE motors to use the [latest Phoenix API](https://api.ctr-electronics.com/changelog#added-20240229).

This sounds like something we should look into:
```
    (Talon FX (v6): 24.4.0.3) In response to recent Kraken RMAs, various adjustments were made to the performance/thermal management.
    (Talon FX (v6): 24.4.0.3) Various changes were applied to Duty Cycle FOC and Voltage FOC to improve efficiency and reduce heat. TorqueCurrentFOC and non-FOC control modes are unaffected.
```

**Project Scope**
- [ ] Update the vendor dep
- [ ] Update firmware

**Comment by redPlover** [comment]
The API is already updated to the latest version
