### ISSUE TITLE
Add even better autos for VAFAL

### ISSUE THREAD

**Issue by jkleiber** [team401/2024-Robot-Code#150]
**Purpose**
The purpose of this addition is to make better, faster, and higher scoring autos for Falls Church.

**Auto Options**
- [x] Pure 6 note (need to be able to drive fast, vision support)
- [x] 2 notes from centerline
- [x] 3 notes from centerline
- [x] Any 4 notes off the floor from any start position

**Comment by aidnem** [comment]
@jkleiber What did you mean by "Any 4notes off the floor from any start position"? Should I just make a few 5-note autos (4 off the ground + 1 starting note) to have as options, or did you mean something else?

**Comment by jkleiber** [comment]
@aidnem Basically if we can add useful/complimentary 5 note autos from each start position that is the goal

**Comment by jkleiber** [comment]
Reopening to track auto work still in progress prior to the event
