### ISSUE TITLE
Optimize driver displays and controls for driver preferences

### ISSUE THREAD

**Issue by jkleiber** [team401/2024-Robot-Code#151]
**Purpose**
The purpose of this ticket is to optimize the driver controls so they get the most out of the robot with the least amount of effort. Here are some initial ideas:
- Auto align enabled with trigger hold or press, but disabled by moving the rotation stick a certain amount when the trigger is not being held
- Get LEDs to work so the driver understands what the robot is doing rather than needing to ask or look anywhere that is not the robot
- Heading snap auto alignment by joystick POV

**Project Scope**
- [x] Sit down with the driver and collect initial high level desires
  - This should focus on features, rather than implementation details.
- [ ] Implement the requested features
- [ ] Practice with the features
- [ ] Iterate as needed until the driver is comfortable with the setup

**Comment by charlesmackenzie** [comment]
Some comments from the driver:
- We should have re-localization points on different sides of the subwoofer
- Holding the right trigger should enable robot-relative drive
- The driver should be able to snap the robot to cardinal headings in a temporary way that doesn't contradict the masher's target
