### ISSUE TITLE
Add VSCode Formatting Settings (Also Maybe a Linter)

### ISSUE THREAD

**Issue by FujiBookPro** [team401/2024-Robot-Code#2]
**Description**
We need a way to easily enforce our style rules from within the editor and GitHub.

**Project Scope**
- [x] Add formatting rules to `/.vscode/`
- [ ] Add a linter to `/.vscode/`, if possible
- [x] Add formatting to our ci pipeline

**Comment by jkleiber** [comment]
If we use spotless as in #32, I don't think we need to configure `.vscode/` - instead we can do the configuration in build.gradle

**Comment by jkleiber** [comment]
I'm going to close this for now unless/until we decide we really want a linter
