### ISSUE TITLE
Add Coppercore dependency

### ISSUE THREAD

**Issue by aidnem** [team401/2024-Robot-Code#201]
**Purpose**
The purpose of this addition is to add Coppercore as a submodule and get it to build properly.

**Project Scope**
- [ ] Add coppercore as a submodule.
- [ ] Update gradle config to include coppercore.
- [ ] Replace 2024-Robot-Code implementations with calls to Coppercore instead.

**Comment by jkleiber** [comment]
Closing this since jitpack is preferred
