### ISSUE TITLE
Re-tune Swerve constants for main robot drivetrain

### ISSUE THREAD

**Issue by jkleiber** [team401/2024-Robot-Code#21]
**Summary**
The TunerConstants are currently set up for the 2023 robot. We need to update them to the 2024 drivebase once it is built

**Work scope**
- Update swerve constants for 2024 chassis
- Test that the code works

**Comment by jkleiber** [comment]
@redPlover @charlesmackenzie is this ready to close?

**Comment by redPlover** [comment]
I would like to wait and tune the robot when we have the superstructure (to account for weight). We could also do that with another issue.

**Comment by jkleiber** [comment]
Makes sense, let's keep this open then
