### ISSUE TITLE
Calibrate Cameras in PhotonVision

### ISSUE THREAD

**Issue by jkleiber** [team401/2024-Robot-Code#24]
**Summary**
Calibration work was underway on 1/13 for cameras on the 2023 robot. This may need to be re-done for future cameras for 2024.

@charlesmackenzie feel free to close this issue if the work is complete or no longer required.

**Comment by PChild** [comment]
Can we use [calibdb](https://www.calibdb.net/) to get camera intrinsics instead of the Photonvision calibration? The error comparison in [this report](https://docs.google.com/document/d/1DAPOnU2NfOp91UnMQnkhyiUAanlCDJ6zl_YsCkCMZdA/edit) make it seem like an easy win to improve accuracy

**Comment by PChild** [comment]
@charlesmackenzie [Here's the Java camera calibrator](https://github.com/tom131313/calibrate/) we had talked about. Sorry I forgot about it for so long

**Comment by PChild** [comment]
Photonvision added [instructions for mrcal](https://docs.photonvision.org/en/latest/docs/calibration/calibration.html#investigating-calibration-data-with-mrcal) which is supposed to be even better.

**Comment by FujiBookPro** [comment]
Calibration data from calibdb for all of our new cameras has been uploaded to Google Drive
