### ISSUE TITLE
Create robot test plan

### ISSUE THREAD

**Issue by jkleiber** [team401/2024-Robot-Code#47]
**Purpose**
The purpose of this issue is to develop a test plan for the robot. The goal of this test plan is to verify the subsystem behavior on the robot.

Additionally, this plan will help us tune the following parameters:
- Shooter angle/RPM control gains
- Shooter hood control gains
- Drivetrain control gains
- Intake belt motor voltages
- Endgame current limits and voltages/gains
- Angles and RPMs required for shooting at variable distances from the speaker
- Time to drop the shooter angle based on position
- Anticipation distance for shoot on the move

**Project Scope**
- [x] Develop test plan for verifying robot functions
- [x] Develop a tuning plan for determining gains and parameters for subsystems
- [x] Create test modes to perform these tests
- [x] Create a test dashboard for these test modes

**Comment by jkleiber** [comment]
@redPlover @charlesmackenzie I've started a document here: https://docs.google.com/document/d/1Q0RYd344qq8yRoueZuRTNFPpY1EmJdiOKtMOQQR6ShU/edit

I focused on making the subsystem verification plan but we need to write down how we are going to do the shooter test

**Comment by redPlover** [comment]
I'll start working on the "tune mode" for testing

**Comment by jkleiber** [comment]
This is effectively done by the work in the scoring integration branch. Any future work can be captured in separate issues
