### ISSUE TITLE
Test Disabling RoboRIO Web Server

### ISSUE THREAD

**Issue by PChild** [team401/2024-Robot-Code#52]
**Purpose**
AdvantageKit can be more memory intensive than a stock wpilib project, disabling the RIO web server can buy us a bit more RAM back. A recent [wpilib update ](https://github.com/wpilibsuite/allwpilib/pull/6270) added the ability to disable and reenable the webserver through a GUI. It would be good to compare RIO free memory running our current code, after disabling the web server, and after replacing lvrt.

Details on replacing lvrt are available in [this ChiefDelphi post](https://www.chiefdelphi.com/t/fatal-robot-code-crash/427074/44)

**Project Scope**
- [x] Update a roboRIO / all of our roboRIOs to 2024
- [x] Record free memory when running our 2024 code
- [x] Disable RIO web server, rerecord free memory
- [x] Check for persistence of disabling the server
- [x] Check that re-enabling the server works correctly
- [x] Test replacing lvrt on the RIO, rerecord free memory

**Comment by redPlover** [comment]
## Here are the performance improvements of disabling the webserver and lvrt. All of these are with the drivetrain code running.

### Normal
![snapshot-1-drive](https://github.com/team401/2024-Robot-Code/assets/100500945/0edfd554-62d1-4980-9385-8a1d74d2a701)
### Webserver Disabled
![snapshot-2-drive-webserver-disabled](https://github.com/team401/2024-Robot-Code/assets/100500945/53882d10-39aa-4232-a4af-b70bec4d4453)
### Webserver & LVRT Disabled
![snapshot-3-lvrt-switched](https://github.com/team401/2024-Robot-Code/assets/100500945/5c55088a-d494-4430-b888-b4683af232e2)

**Comment by jkleiber** [comment]
What exactly are we looking for in these pictures?

**Comment by PChild** [comment]
Our rough testing showed that the (drive only) robot program was using ~10 MB of RAM. I'd like to check later in the season when we have more subsystems enabled and see how memory use compares.
