### ISSUE TITLE
Apply simulation to AdvantageScope

### ISSUE THREAD

**Issue by redPlover** [team401/2024-Robot-Code#9]
**Project Scope**
- [ ] Robot Model Puppeteering
- [ ] Ensure that model logging is working

**Comment by PChild** [comment]
I started exporting models for this today, it's not 100% since we do have a lot of refinement to do, but I think it'll be close enough that you can start puppeteering and swap in more accurate models once we're done.

**Comment by redPlover** [comment]
Okay, I've added the mechanism2d for the scoring subsystem and will send it out as a PR tomorrow.

**Comment by PChild** [comment]
GLB files for each system are now posted in the team Google Drive: 
2024 Controls > Main Robot > GLB Files

Based on [the docs](https://github.com/Mechanical-Advantage/AdvantageScope/blob/main/docs/CUSTOM-ASSETS.md#3d-robot-models) it sounds like you need zeroed positions and angles, check the OnShape model for those.

**Comment by redPlover** [comment]
Thanks

**Comment by redPlover** [comment]
Done in #64
